apiVersion: apps/v1
kind: Deployment
metadata:
  name: demowtappapi
  labels:
    app: demowtappapi
    
  namespace: demowt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demowtappapi
  strategy: {}
  template:
    metadata:
      labels:
        app: demowtappapi
    spec:
      containers:
      - image: kokisoft/newtimwtapi:1145
        name: demowtappapi
        ports:
          - name: http
            containerPort: 5000
            protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: deployhome
        resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
        args:
              - -cpus
              - "2" 