apiVersion: v1
kind: Service
metadata:
  name: demowtsvc
  labels:
    app: demowtsvc
    
  namespace: demowt
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: demowtapp
  