kind: ConfigMap
apiVersion: v1
metadata:
  name: restapi-cm
  namespace: testdapr
  labels:
    app: testdapr
    service: restapi
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: restapi
  namespace: testdapr
  labels:
    app: testdapr
    service: restapi
spec:
  replicas: 2
  selector:
    matchLabels:
      service: restapi
  template:
    metadata:
      labels:
         app: testdapr
         service: restapi
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "rincloudadmin-api"
        dapr.io/app-port: "80"
        dapr.io/config: "dapr-config"
        #dapr.io/app-protocol: "grpc"
    spec:
      containers:
      - name: restapi
        image: kokisoft/rincloud-restapi:949
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP  
          # - name: admin
          #   containerPort: 8003
          #   protocol: TCP
          # - name: daprhttp
          #   containerPort: 3500
          #   protocol: TCP
          # - name: daprgrpc
          #   containerPort: 50001
          #   protocol: TCP
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        args:
            - -cpus
            - "2"    
        envFrom:
          - configMapRef:
              name: restapi-cm

---

kind: Service
apiVersion: v1
metadata:
  name: restapi
  namespace: testdapr
  labels:
    app: testdapr
    service: restapi
spec:
  ports:
    - port: 80
      name: http 
      targetPort: 80
      protocol: TCP
    - port: 443
      name: https
      targetPort: 443
      protocol: TCP

    #   name: http
    # - port: 8003
    #   targetPort: 8003
    #   protocol: TCP
    #   name: admin
    # - port: 3500
    #   targetPort: 3500
    #   protocol: TCP
    #   name: daprhttp
    # - port: 50001
    #   targetPort: 50001
    #   protocol: TCP
    #   name: daprgrpc
  selector:
    service: restapi