apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: rinpubsub
 
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: connectionString
    value: amqp://dapr:dapr@192.168.11.29:5672/dapr
  - name: host
    value: amqp://dapr:dapr@192.168.11.29:5672/dapr
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel

