apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogymfront
  labels:
    app: demogymfront
  namespace: demogym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demogymfront
  strategy: {}
  template:
    metadata:
      labels:
        app: demogymfront
    spec:
      containers:
      - image: kokisoft/gym6web:1123
        name: demogymfront
        readinessProbe: null
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        args:
              - -cpus
              - "1" 