apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogymlocker
  labels:
    app: demogymlocker
    
  namespace: demogym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demogymlocker
  strategy: {}
  template:
    metadata:
      labels:
        app: demogymlocker
    spec:
      containers:
      - image: kokisoft/gym6locker:1128
        name: demogymlocker
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
        args:
              - -cpus
              - "2" 