apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogymapi
  labels:
    app: demogymapi
    
  namespace: demogym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demogymapi
  strategy: {}
  template:
    metadata:
      labels:
        app: demogymapi
    spec:
      containers:
      - image: kokisoft/gym6api:1126
        name: demogymapi
        ports:
          - name: http
            containerPort: 5200
            protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: ev
        - name: enableHang
          value: "false"

        resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
        args:
              - -cpus
              - "2" 