apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogymfront
  labels:
    app: demogymfront
  namespace: demogym
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demogymfront
  strategy: {}
  template:
    metadata:
      labels:
        app: demogymfront
    spec:
      containers:
      - image: kokisoft/gym6web:1133
        name: demogymfront
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
