apiVersion: v1
kind: Service
metadata:
  name: demogymlockersvc
  labels:
    app: demogymlockersvc
    
  namespace: demogym
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: demogymlocker
  