apiVersion: v1
kind: Service
metadata:
  name: demogymfrontsvc
  labels:
    app: demogymfrontsvc
    
  namespace: demogym
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: demogymfront
  