apiVersion: v1
kind: Service
metadata:
  name: demogymapisvc
  labels:
    app: demogymapisvc
    
  namespace: demogym
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5200
  selector:
    app: demogymapi
  