apiVersion: v1
kind: Service
metadata:
  labels:
    app: id-sts
  name: id-sts
  namespace: rinidentity
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: id
  