apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfcmanager
  labels:
    app: nfcmanager
    
  namespace: nfcmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfcmanager
  strategy: {}
  template:
    metadata:
      labels:
        app: nfcmanager
    spec:
      containers:
      - image: kokisoft/nfcmanager:10
        name: nextcloudproxy
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP

        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
        args:
              - -cpus
              - "1" 