apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfcmanager
  labels:
    app: nfcmanager
    
  namespace: nfcmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfcmanager
  strategy: {}
  template:
    metadata:
      labels:
        app: nfcmanager
    spec:
      containers:
        - image: kokisoft/nfcmanager:16
          name: nextcloudproxy
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5