apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfcmanager
  labels:
    app: nfcmanager
    
  namespace: nfcmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfcmanager
  strategy: {}
  template:
    metadata:
      labels:
        app: nfcmanager
    spec:
      containers:
      - image: kokisoft/nfcmanager:14
        name: nextcloudproxy
        ports:
          - name: http
            containerPort: 3000
            protocol: TCP

