apiVersion: v1
kind: Service
metadata:
  name: nfc-manager-service
  namespace: nfcmanager
spec:
  selector:
    app: nfc-manager
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30000
  type: NodePort 