apiVersion: v1
kind: Service
metadata:
  name: nfcmanagersvc
  labels:
    app: nfcmanagersvc
    
  namespace: nfcmanager
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000

  selector:
    app: nfcmanager