apiVersion: apps/v1
kind: Deployment
metadata:
  name: identityapp
  labels:
    app: identityapp
    
  namespace: devidentity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identityapp
  strategy: {}
  template:
    metadata:
      labels:
        app: identityapp
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "sts"
        dapr.io/app-port: "8080"
        dapr.io/config: "dapr-config"
        dapr.io/app-protocol: "http"
        #dapr.io/app-protocol: "grpc"  
    spec:
      hostAliases:
       - ip: "192.168.10.100"
         hostnames:
          - "admin-devlogin.rinsoftware.com"
          - "devlogin.rinsoftware.com"
      containers:
      - image: kokisoft/rincloudidentity:1044
        name: identityapp
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: rindev
        resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
        args:
              - -cpus
              - "2" 