apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: identity
  name: identity
  namespace: devidentity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  strategy: {}
  template:
    metadata:
      labels:
        app: identity
    spec:
      hostAliases:
       - ip: "192.168.10.100"
         hostnames:
          - "login.rin-cloud.eu"
          - "sts.book-cloud.eu"
      containers:
      - image: kokisoft/rincloudidentity:982
        name: identity
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
          - name: https
            containerPort: 443
            protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
        args:
              - -cpus
              - "2" 