apiVersion: v1
kind: Service
metadata:
  name: identityadminsvc
  labels:
    app: identityadminsvc
    
  namespace: devidentity
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: identityadminapp
  