apiVersion: v1
kind: Service
metadata:
  labels:
    app: identitysvc
    name: identitysvc
  namespace: devidentity
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: identityapp
  